apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-management
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-management
  template:
    metadata:
      labels:
        app: students-management
    spec:
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
